// @vitest-environment node
import { describe, it, expect } from 'vitest'
import { parseDirectDepNames, toRequirementsTxt, parseNuGetLock } from './parser'

const REQUIREMENTS_TXT = `
# a comment
requests>=2.28.0
fastapi==0.100.0
  httpx
-r other.txt
--index-url https://example.com
`

const POETRY_LOCK = `
# This file is automatically @generated by Poetry and should not be altered by hand.

[[package]]
name = "requests"
version = "2.28.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"

[[package]]
name = "urllib3"
version = "1.26.18"
description = "HTTP library with thread-safe connection pooling."
optional = false
python-versions = ">=2.7"

[[package]]
name = "fastapi"
version = "0.100.0"
description = "FastAPI framework."
optional = false
python-versions = ">=3.7"

[metadata]
lock-version = "2.0"
python-versions = "^3.11"
content-hash = "abc123"
`

describe('parseDirectDepNames', () => {
  it('extracts names from requirements.txt, skipping comments and options', () => {
    expect(parseDirectDepNames('requirements.txt', REQUIREMENTS_TXT)).toEqual(['requests', 'fastapi', 'httpx'])
  })

  it('extracts root package names from poetry.lock (no deps defined → all are roots)', () => {
    expect(parseDirectDepNames('poetry.lock', POETRY_LOCK)).toEqual(['requests', 'urllib3', 'fastapi'])
  })

  it('excludes transitive packages from poetry.lock direct names', () => {
    const lockWithDeps = `
[[package]]
name = "requests"
version = "2.28.0"

[package.dependencies]
urllib3 = ">=1.21.1"
certifi = ">=2017.4.17"

[[package]]
name = "urllib3"
version = "1.26.18"

[[package]]
name = "certifi"
version = "2023.7.22"
`
    // urllib3 and certifi are deps of requests → only requests is a root
    expect(parseDirectDepNames('poetry.lock', lockWithDeps)).toEqual(['requests'])
  })

  it('returns lowercase names', () => {
    expect(parseDirectDepNames('requirements.txt', 'Requests>=2.0\n')).toEqual(['requests'])
  })
})

const NUGET_LOCK = JSON.stringify({
  version: 1,
  dependencies: {
    'net8.0': {
      'Newtonsoft.Json': { type: 'Direct', resolved: '13.0.3', dependencies: { 'System.Runtime': '[4.3.0, )' } },
      'Microsoft.Extensions.Logging': { type: 'Direct', resolved: '8.0.0', dependencies: {} },
      'System.Runtime': { type: 'Transitive', resolved: '4.3.0', dependencies: {} },
    },
  },
})

describe('parseNuGetLock', () => {
  it('separates direct and transitive packages', () => {
    const { packages, directNames } = parseNuGetLock(NUGET_LOCK)
    expect(directNames.has('newtonsoft.json')).toBe(true)
    expect(directNames.has('microsoft.extensions.logging')).toBe(true)
    expect(directNames.has('system.runtime')).toBe(false)
    expect(packages).toHaveLength(3)
  })

  it('records immediate dependency names for each package', () => {
    const { packages } = parseNuGetLock(NUGET_LOCK)
    const json = packages.find(p => p.name === 'Newtonsoft.Json')!
    expect(json.deps).toEqual(['System.Runtime'])
  })

  it('records resolved version', () => {
    const { packages } = parseNuGetLock(NUGET_LOCK)
    const json = packages.find(p => p.name === 'Newtonsoft.Json')!
    expect(json.version).toBe('13.0.3')
  })

  it('deduplicates packages that appear in multiple target frameworks', () => {
    const multiFramework = JSON.stringify({
      version: 1,
      dependencies: {
        'net8.0': { 'Newtonsoft.Json': { type: 'Direct', resolved: '13.0.3', dependencies: {} } },
        'net6.0': { 'Newtonsoft.Json': { type: 'Direct', resolved: '13.0.3', dependencies: {} } },
      },
    })
    const { packages } = parseNuGetLock(multiFramework)
    expect(packages).toHaveLength(1)
  })
})

describe('toRequirementsTxt', () => {
  it('returns requirements.txt content unchanged', () => {
    expect(toRequirementsTxt('requirements.txt', 'requests>=2.0\n')).toBe('requests>=2.0\n')
  })

  it('converts poetry.lock to pinned requirements format', () => {
    const result = toRequirementsTxt('poetry.lock', POETRY_LOCK)
    expect(result).toContain('requests==2.28.0')
    expect(result).toContain('urllib3==1.26.18')
    expect(result).toContain('fastapi==0.100.0')
  })
})
